.TH "My_struct" 3 "Вт 26 Янв 2016" "Version текущая версия: 1.0" "EmbedPROFILER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
My_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Поля данных"

.in +1c
.ti -1c
.RI "volatile float \fBI\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле profiler_example\&.cpp строка 21

.SH "Автор"
.PP 
Автоматически создано Doxygen для EmbedPROFILER из исходного текста\&.
