.TH "Портируемая_секция" 3 "Вт 26 Янв 2016" "Version текущая версия: 1.0" "EmbedPROFILER" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Портируемая_секция \- 
.PP
Эти функции необходимо определить для вашей платформы\&. Остальная часть кода профилировщика является платформо-независимой\&.  

.SS "Макросы"

.in +1c
.ti -1c
.RI "#define \fBPROFILER_TOTAL_PROFILERS\fP   1024"
.br
.RI "\fIМаксимальное число работающих профилировщиков времени вызова\&. \fP"
.ti -1c
.RI "#define \fBPROFILER_global_stop\fP()   \fBPROFILER_local_stop\fP()"
.br
.RI "\fIОкончание работы глобального профилировщика\&. \fP"
.in -1c
.SS "Определения типов"

.in +1c
.ti -1c
.RI "typedef struct timespec \fBPROFILER_timestruct\fP"
.br
.RI "\fIТип переменной для хранения измерений времени\&. \fP"
.in -1c
.SS "Функции"

.in +1c
.ti -1c
.RI "void \fBPROFILER_log\fP ()"
.br
.RI "\fIВывести отчёт о работе профилировщика\&. \fP"
.ti -1c
.RI "void \fBPROFILER_get_current_time\fP (\fBPROFILER_timestruct\fP *PROFILER_timestruct_instance)"
.br
.RI "\fIПолучить текущее время в системе\&. \fP"
.ti -1c
.RI "void \fBPROFILER_refresh_time_consumed\fP (\fBPROFILER_timestruct\fP PROFILER_begin_time, \fBPROFILER_timestruct\fP PROFILER_end_time, int32_t PROFILER_instance_index)"
.br
.RI "\fIОбновить общее время затраченное на работу указанного профилировщика за все его вызовы\&. \fP"
.in -1c
.SH "Подробное описание"
.PP 
Эти функции необходимо определить для вашей платформы\&. Остальная часть кода профилировщика является платформо-независимой\&. 

EmbedPROFILER проектировался для исполнения во встраиваемых системах независимо от аппаратной платформы\&. Для того, чтобы EmbedPROFILER можно было перенести на интересующую вас платформу, необходимо реализовать на данной платформе определённые в этой секции процедуры и макросы\&. 
.SH "Макросы"
.PP 
.SS "#define \fBPROFILER_global_stop\fP()   \fBPROFILER_local_stop\fP()"
.PP
Окончание работы глобального профилировщика\&. Запоминается время окончания работы системы профилирования\&. Которое используется в дальнейшем для расчёта времени работы системы профилирования\&.Добавлено в портируемый раздел, поскольку завершение работы профилировщика может быть платформо-зависимой\&. 
.PP
См\&. определение в файле PROFILING_tools\&.h строка 256
.SS "#define \fBPROFILER_TOTAL_PROFILERS\fP   1024"
.PP
Максимальное число работающих профилировщиков времени вызова\&. Это число определяет размеры массивов для хранения указателей на названия функций, имена файлов, номера строк и число вызовов\&. 
.PP
См\&. определение в файле PROFILING_tools\&.h строка 67
.SH "Типы"
.PP 
.SS "\fBPROFILER_timestruct\fP"
.PP
Тип переменной для хранения измерений времени\&. Для оптимальной работы не рекомендуется хранение времени в целочисленных типах\&. 
.PP
См\&. определение в файле PROFILING_tools\&.h строка 58
.SH "Функции"
.PP 
.SS "\fBPROFILER_get_current_time\fP (\fBPROFILER_timestruct\fP *PROFILER_timestruct_instance)"
.PP
Получить текущее время в системе\&. \fBАргументы:\fP
.RS 4
\fIPROFILER_timestruct\fP *PROFILER_timestruct_instance 
.br
 Указатель на структуру, в которой будет сохранено системное время\&. 
.RE
.PP

.PP
См\&. определение в файле PROFILING_tools\&.h строка 151
.SS "void \fBPROFILER_log\fP ()"
.PP
Вывести отчёт о работе профилировщика\&. Сообщает затраченное на работу каждого профилировщика время, имена файлов, номера строк, названия функций где был создан данный профилировщик\&. Также сообщает число вызовов данного профилировщика\&. 
.PP
См\&. определение в файле PROFILING_tools\&.c строка 94
.SS "void \fBPROFILER_refresh_time_consumed\fP (\fBPROFILER_timestruct\fPPROFILER_begin_time, \fBPROFILER_timestruct\fPPROFILER_end_time, int32_tPROFILER_instance_index)"
.PP
Обновить общее время затраченное на работу указанного профилировщика за все его вызовы\&. Добавляет время потраченное указанным профилировщиком за последний вызов к общему времени за все вызовы, затраченному указанным профилировщиком\&. 
.PP
\fBАргументы:\fP
.RS 4
\fIPROFILER_timestruct\fP PROFILER_begin_time 
.br
 Время начала работы (очередного вызова) локального профилировщика\&. 
.br
\fIPROFILER_timestruct\fP PROFILER_end_time 
.br
 Время окончания работы (очередного завершения) локального профилировщика\&. 
.br
\fIint32_t\fP PROFILER_instance_index 
.br
 Индекс локального профилировщика\&. 
.RE
.PP

.PP
См\&. определение в файле PROFILING_tools\&.h строка 169
.SH "Автор"
.PP 
Автоматически создано Doxygen для EmbedPROFILER из исходного текста\&.
